agent:
  name: "CustomerServiceAgent"
  model: "gemini-2.5-flash"
  thinking_budget: 0
server:
  host: "0.0.0.0"
  port: 8000
db:
  path: "./src/db/agent_data.db"
tools:
  kb_top_k: 5
email:
  smtp_host: "smtp.example.com"
  smtp_port: 587
  from_addr: "support@example.com"
